version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: MainProgram/Dockerfile
    container_name: main-api
    restart: always
    depends_on:
      - users-db
      - posts-db
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"

  users-db:
    image: postgres:latest
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyui
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  posts-db:
    image: postgres:latest
    container_name: posts-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyui
      POSTGRES_DB: posts
    ports:
      - "5433:5432"
    volumes:
      - posts_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-access-key
      MINIO_ROOT_PASSWORD: minio-secret-key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  users_data:
  posts_data:
  minio_data:
